<?php

/**
 * BaseDiagnosis
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $group_id
 * @property string $code
 * @property string $name
 * @property string $description
 * @property string $active
 * @property Group $Group
 * @property Doctrine_Collection $Treatments
 * @property Doctrine_Collection $TreatmentDiagnosis
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getGroupId()            Returns the current record's "group_id" value
 * @method string              getCode()               Returns the current record's "code" value
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getDescription()        Returns the current record's "description" value
 * @method string              getActive()             Returns the current record's "active" value
 * @method Group               getGroup()              Returns the current record's "Group" value
 * @method Doctrine_Collection getTreatments()         Returns the current record's "Treatments" collection
 * @method Doctrine_Collection getTreatmentDiagnosis() Returns the current record's "TreatmentDiagnosis" collection
 * @method Diagnosis           setId()                 Sets the current record's "id" value
 * @method Diagnosis           setGroupId()            Sets the current record's "group_id" value
 * @method Diagnosis           setCode()               Sets the current record's "code" value
 * @method Diagnosis           setName()               Sets the current record's "name" value
 * @method Diagnosis           setDescription()        Sets the current record's "description" value
 * @method Diagnosis           setActive()             Sets the current record's "active" value
 * @method Diagnosis           setGroup()              Sets the current record's "Group" value
 * @method Diagnosis           setTreatments()         Sets the current record's "Treatments" collection
 * @method Diagnosis           setTreatmentDiagnosis() Sets the current record's "TreatmentDiagnosis" collection
 * 
 * @package    saludonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDiagnosis extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_diagnosis');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('group_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'notnull' => true,
             ));
        $this->hasColumn('code', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 1,
             ));


        $this->index('u_code', array(
             'fields' => 
             array(
              0 => 'code',
             ),
             'type' => 'unique',
             ));
        $this->index('i_active', array(
             'fields' => 
             array(
              0 => 'active',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Group', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('Treatment as Treatments', array(
             'refClass' => 'TreatmentDiagnosis',
             'local' => 'diagnosis_id',
             'foreign' => 'treatment_id'));

        $this->hasMany('TreatmentDiagnosis', array(
             'local' => 'id',
             'foreign' => 'diagnosis_id'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
    }
}