<?php

/**
 * BasePatient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $realname
 * @property string $username
 * @property string $password
 * @property string $email
 * @property string $url
 * @property string $twitter_username
 * @property string $phone
 * @property string $active
 * @property timestamp $last_access_at
 * @property string $facebook_id
 * @property Doctrine_Collection $Profiles
 * @property Doctrine_Collection $Doctors
 * @property Doctrine_Collection $Contacts
 * @property Doctrine_Collection $Resources
 * @property Doctrine_Collection $ContactPatient
 * @property Doctrine_Collection $DoctorPatient
 * @property Doctrine_Collection $PatientProfile
 * @property Doctrine_Collection $ResourcePatient
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getRealname()         Returns the current record's "realname" value
 * @method string              getUsername()         Returns the current record's "username" value
 * @method string              getPassword()         Returns the current record's "password" value
 * @method string              getEmail()            Returns the current record's "email" value
 * @method string              getUrl()              Returns the current record's "url" value
 * @method string              getTwitterUsername()  Returns the current record's "twitter_username" value
 * @method string              getPhone()            Returns the current record's "phone" value
 * @method string              getActive()           Returns the current record's "active" value
 * @method timestamp           getLastAccessAt()     Returns the current record's "last_access_at" value
 * @method string              getFacebookId()       Returns the current record's "facebook_id" value
 * @method Doctrine_Collection getProfiles()         Returns the current record's "Profiles" collection
 * @method Doctrine_Collection getDoctors()          Returns the current record's "Doctors" collection
 * @method Doctrine_Collection getContacts()         Returns the current record's "Contacts" collection
 * @method Doctrine_Collection getResources()        Returns the current record's "Resources" collection
 * @method Doctrine_Collection getContactPatient()   Returns the current record's "ContactPatient" collection
 * @method Doctrine_Collection getDoctorPatient()    Returns the current record's "DoctorPatient" collection
 * @method Doctrine_Collection getPatientProfile()   Returns the current record's "PatientProfile" collection
 * @method Doctrine_Collection getResourcePatient()  Returns the current record's "ResourcePatient" collection
 * @method Patient             setId()               Sets the current record's "id" value
 * @method Patient             setRealname()         Sets the current record's "realname" value
 * @method Patient             setUsername()         Sets the current record's "username" value
 * @method Patient             setPassword()         Sets the current record's "password" value
 * @method Patient             setEmail()            Sets the current record's "email" value
 * @method Patient             setUrl()              Sets the current record's "url" value
 * @method Patient             setTwitterUsername()  Sets the current record's "twitter_username" value
 * @method Patient             setPhone()            Sets the current record's "phone" value
 * @method Patient             setActive()           Sets the current record's "active" value
 * @method Patient             setLastAccessAt()     Sets the current record's "last_access_at" value
 * @method Patient             setFacebookId()       Sets the current record's "facebook_id" value
 * @method Patient             setProfiles()         Sets the current record's "Profiles" collection
 * @method Patient             setDoctors()          Sets the current record's "Doctors" collection
 * @method Patient             setContacts()         Sets the current record's "Contacts" collection
 * @method Patient             setResources()        Sets the current record's "Resources" collection
 * @method Patient             setContactPatient()   Sets the current record's "ContactPatient" collection
 * @method Patient             setDoctorPatient()    Sets the current record's "DoctorPatient" collection
 * @method Patient             setPatientProfile()   Sets the current record's "PatientProfile" collection
 * @method Patient             setResourcePatient()  Sets the current record's "ResourcePatient" collection
 * 
 * @package    saludonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePatient extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_patient');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('realname', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => true,
             ));
        $this->hasColumn('username', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'notnull' => true,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('twitter_username', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('phone', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('last_access_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('facebook_id', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));


        $this->index('i_username', array(
             'fields' => 
             array(
              0 => 'username',
             ),
             ));
        $this->index('u_email', array(
             'fields' => 
             array(
              0 => 'email',
             ),
             'type' => 'unique',
             ));
        $this->index('u_facebook_id', array(
             'fields' => 
             array(
              0 => 'facebook_id',
             ),
             'type' => 'unique',
             ));
        $this->index('i_url', array(
             'fields' => 
             array(
              0 => 'url',
             ),
             ));
        $this->index('i_twitter_username', array(
             'fields' => 
             array(
              0 => 'twitter_username',
             ),
             ));
        $this->index('i_active', array(
             'fields' => 
             array(
              0 => 'active',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Profile as Profiles', array(
             'refClass' => 'PatientProfile',
             'local' => 'patient_id',
             'foreign' => 'profile_id'));

        $this->hasMany('Doctor as Doctors', array(
             'refClass' => 'DoctorPatient',
             'local' => 'patient_id',
             'foreign' => 'doctor_id'));

        $this->hasMany('Contact as Contacts', array(
             'refClass' => 'ContactPatient',
             'local' => 'patient_id',
             'foreign' => 'contact_id'));

        $this->hasMany('Resource as Resources', array(
             'refClass' => 'ResourcePatient',
             'local' => 'patient_id',
             'foreign' => 'resource_id'));

        $this->hasMany('ContactPatient', array(
             'local' => 'id',
             'foreign' => 'patient_id'));

        $this->hasMany('DoctorPatient', array(
             'local' => 'id',
             'foreign' => 'patient_id'));

        $this->hasMany('PatientProfile', array(
             'local' => 'id',
             'foreign' => 'patient_id'));

        $this->hasMany('ResourcePatient', array(
             'local' => 'id',
             'foreign' => 'patient_id'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'username',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
    }
}