<?php

/**
 * BaseGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $chapter_id
 * @property string $code
 * @property string $name
 * @property string $description
 * @property string $active
 * @property Chapter $Chapter
 * @property Doctrine_Collection $Diagnosis
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getChapterId()   Returns the current record's "chapter_id" value
 * @method string              getCode()        Returns the current record's "code" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getActive()      Returns the current record's "active" value
 * @method Chapter             getChapter()     Returns the current record's "Chapter" value
 * @method Doctrine_Collection getDiagnosis()   Returns the current record's "Diagnosis" collection
 * @method Group               setId()          Sets the current record's "id" value
 * @method Group               setChapterId()   Sets the current record's "chapter_id" value
 * @method Group               setCode()        Sets the current record's "code" value
 * @method Group               setName()        Sets the current record's "name" value
 * @method Group               setDescription() Sets the current record's "description" value
 * @method Group               setActive()      Sets the current record's "active" value
 * @method Group               setChapter()     Sets the current record's "Chapter" value
 * @method Group               setDiagnosis()   Sets the current record's "Diagnosis" collection
 * 
 * @package    saludonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroup extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_group');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('chapter_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'notnull' => true,
             ));
        $this->hasColumn('code', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 1,
             ));


        $this->index('u_code', array(
             'fields' => 
             array(
              0 => 'code',
             ),
             'type' => 'unique',
             ));
        $this->index('i_active', array(
             'fields' => 
             array(
              0 => 'active',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Chapter', array(
             'local' => 'chapter_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('Diagnosis', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
    }
}