<?php

/**
 * BasePostCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $post_id
 * @property integer $category_id
 * @property Post $Post
 * @property Category $Category
 * 
 * @method integer      getPostId()      Returns the current record's "post_id" value
 * @method integer      getCategoryId()  Returns the current record's "category_id" value
 * @method Post         getPost()        Returns the current record's "Post" value
 * @method Category     getCategory()    Returns the current record's "Category" value
 * @method PostCategory setPostId()      Sets the current record's "post_id" value
 * @method PostCategory setCategoryId()  Sets the current record's "category_id" value
 * @method PostCategory setPost()        Sets the current record's "Post" value
 * @method PostCategory setCategory()    Sets the current record's "Category" value
 * 
 * @package    saludonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostCategory extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_post_category');
        $this->hasColumn('post_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}