<?php

/**
 * BaseVisit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $remote_address
 * @property string $remote_port
 * @property string $http_user_agent
 * @property datetime $datetime
 * 
 * @method integer  getId()              Returns the current record's "id" value
 * @method string   getRemoteAddress()   Returns the current record's "remote_address" value
 * @method string   getRemotePort()      Returns the current record's "remote_port" value
 * @method string   getHttpUserAgent()   Returns the current record's "http_user_agent" value
 * @method datetime getDatetime()        Returns the current record's "datetime" value
 * @method Visit    setId()              Sets the current record's "id" value
 * @method Visit    setRemoteAddress()   Sets the current record's "remote_address" value
 * @method Visit    setRemotePort()      Sets the current record's "remote_port" value
 * @method Visit    setHttpUserAgent()   Sets the current record's "http_user_agent" value
 * @method Visit    setDatetime()        Sets the current record's "datetime" value
 * 
 * @package    saludonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVisit extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_visit');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('remote_address', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'notnull' => true,
             ));
        $this->hasColumn('remote_port', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'notnull' => true,
             ));
        $this->hasColumn('http_user_agent', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));
        $this->hasColumn('datetime', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));


        $this->index('i_remote_address', array(
             'fields' => 
             array(
              0 => 'remote_address',
             ),
             ));
        $this->index('i_datetime', array(
             'fields' => 
             array(
              0 => 'datetime',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}