<?php

/**
 * BaseResource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $path
 * @property integer $size
 * @property string $full_mime
 * @property integer $rank
 * @property Doctrine_Collection $Patients
 * @property Doctrine_Collection $ResourcePatient
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getPath()            Returns the current record's "path" value
 * @method integer             getSize()            Returns the current record's "size" value
 * @method string              getFullMime()        Returns the current record's "full_mime" value
 * @method integer             getRank()            Returns the current record's "rank" value
 * @method Doctrine_Collection getPatients()        Returns the current record's "Patients" collection
 * @method Doctrine_Collection getResourcePatient() Returns the current record's "ResourcePatient" collection
 * @method Resource            setId()              Sets the current record's "id" value
 * @method Resource            setName()            Sets the current record's "name" value
 * @method Resource            setPath()            Sets the current record's "path" value
 * @method Resource            setSize()            Sets the current record's "size" value
 * @method Resource            setFullMime()        Sets the current record's "full_mime" value
 * @method Resource            setRank()            Sets the current record's "rank" value
 * @method Resource            setPatients()        Sets the current record's "Patients" collection
 * @method Resource            setResourcePatient() Sets the current record's "ResourcePatient" collection
 * 
 * @package    saludonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResource extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_resource');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));
        $this->hasColumn('size', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('full_mime', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));
        $this->hasColumn('rank', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('i_name', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Patient as Patients', array(
             'refClass' => 'ResourcePatient',
             'local' => 'resource_id',
             'foreign' => 'patient_id'));

        $this->hasMany('ResourcePatient', array(
             'local' => 'id',
             'foreign' => 'resource_id'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $thumbnailable0 = new Doctrine_Template_Thumbnailable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
        $this->actAs($thumbnailable0);
    }
}