<?php

/**
 * BaseResourcePatient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $resource_id
 * @property integer $patient_id
 * @property Resource $Resource
 * @property Patient $Patient
 * 
 * @method integer         getResourceId()  Returns the current record's "resource_id" value
 * @method integer         getPatientId()   Returns the current record's "patient_id" value
 * @method Resource        getResource()    Returns the current record's "Resource" value
 * @method Patient         getPatient()     Returns the current record's "Patient" value
 * @method ResourcePatient setResourceId()  Sets the current record's "resource_id" value
 * @method ResourcePatient setPatientId()   Sets the current record's "patient_id" value
 * @method ResourcePatient setResource()    Sets the current record's "Resource" value
 * @method ResourcePatient setPatient()     Sets the current record's "Patient" value
 * 
 * @package    saludonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResourcePatient extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_resource_patient');
        $this->hasColumn('resource_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             ));
        $this->hasColumn('patient_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Resource', array(
             'local' => 'resource_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Patient', array(
             'local' => 'patient_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}