<?php

/**
 * BaseTreatment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $doctor_id
 * @property integer $profile_id
 * @property integer $hospital_id
 * @property date $date_of_treatment
 * @property string $description
 * @property string $active
 * @property Profile $Profile
 * @property Doctor $Doctor
 * @property Hospital $Hospital
 * @property Doctrine_Collection $Diagnosises
 * @property Doctrine_Collection $TreatmentDiagnosis
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getDoctorId()           Returns the current record's "doctor_id" value
 * @method integer             getProfileId()          Returns the current record's "profile_id" value
 * @method integer             getHospitalId()         Returns the current record's "hospital_id" value
 * @method date                getDateOfTreatment()    Returns the current record's "date_of_treatment" value
 * @method string              getDescription()        Returns the current record's "description" value
 * @method string              getActive()             Returns the current record's "active" value
 * @method Profile             getProfile()            Returns the current record's "Profile" value
 * @method Doctor              getDoctor()             Returns the current record's "Doctor" value
 * @method Hospital            getHospital()           Returns the current record's "Hospital" value
 * @method Doctrine_Collection getDiagnosises()        Returns the current record's "Diagnosises" collection
 * @method Doctrine_Collection getTreatmentDiagnosis() Returns the current record's "TreatmentDiagnosis" collection
 * @method Treatment           setId()                 Sets the current record's "id" value
 * @method Treatment           setDoctorId()           Sets the current record's "doctor_id" value
 * @method Treatment           setProfileId()          Sets the current record's "profile_id" value
 * @method Treatment           setHospitalId()         Sets the current record's "hospital_id" value
 * @method Treatment           setDateOfTreatment()    Sets the current record's "date_of_treatment" value
 * @method Treatment           setDescription()        Sets the current record's "description" value
 * @method Treatment           setActive()             Sets the current record's "active" value
 * @method Treatment           setProfile()            Sets the current record's "Profile" value
 * @method Treatment           setDoctor()             Sets the current record's "Doctor" value
 * @method Treatment           setHospital()           Sets the current record's "Hospital" value
 * @method Treatment           setDiagnosises()        Sets the current record's "Diagnosises" collection
 * @method Treatment           setTreatmentDiagnosis() Sets the current record's "TreatmentDiagnosis" collection
 * 
 * @package    saludonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTreatment extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_treatment');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('doctor_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'notnull' => true,
             ));
        $this->hasColumn('profile_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'notnull' => true,
             ));
        $this->hasColumn('hospital_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'notnull' => true,
             ));
        $this->hasColumn('date_of_treatment', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('description', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 1,
             ));


        $this->index('i_active', array(
             'fields' => 
             array(
              0 => 'active',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'profile_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Doctor', array(
             'local' => 'doctor_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Hospital', array(
             'local' => 'hospital_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('Diagnosis as Diagnosises', array(
             'refClass' => 'TreatmentDiagnosis',
             'local' => 'treatment_id',
             'foreign' => 'diagnosis_id'));

        $this->hasMany('TreatmentDiagnosis', array(
             'local' => 'id',
             'foreign' => 'treatment_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}