<?php

/**
 * BaseContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $firstname
 * @property string $lastname
 * @property string $gender
 * @property string $email
 * @property string $home_phone
 * @property string $office_phone
 * @property string $mobile_phone
 * @property string $rpm
 * @property string $rpc
 * @property string $nextel
 * @property string $fax
 * @property string $address_home
 * @property string $address_work
 * @property string $description
 * @property string $prefix
 * @property string $active
 * @property Doctrine_Collection $Patients
 * @property Doctrine_Collection $ContactPatient
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getFirstname()      Returns the current record's "firstname" value
 * @method string              getLastname()       Returns the current record's "lastname" value
 * @method string              getGender()         Returns the current record's "gender" value
 * @method string              getEmail()          Returns the current record's "email" value
 * @method string              getHomePhone()      Returns the current record's "home_phone" value
 * @method string              getOfficePhone()    Returns the current record's "office_phone" value
 * @method string              getMobilePhone()    Returns the current record's "mobile_phone" value
 * @method string              getRpm()            Returns the current record's "rpm" value
 * @method string              getRpc()            Returns the current record's "rpc" value
 * @method string              getNextel()         Returns the current record's "nextel" value
 * @method string              getFax()            Returns the current record's "fax" value
 * @method string              getAddressHome()    Returns the current record's "address_home" value
 * @method string              getAddressWork()    Returns the current record's "address_work" value
 * @method string              getDescription()    Returns the current record's "description" value
 * @method string              getPrefix()         Returns the current record's "prefix" value
 * @method string              getActive()         Returns the current record's "active" value
 * @method Doctrine_Collection getPatients()       Returns the current record's "Patients" collection
 * @method Doctrine_Collection getContactPatient() Returns the current record's "ContactPatient" collection
 * @method Contact             setId()             Sets the current record's "id" value
 * @method Contact             setFirstname()      Sets the current record's "firstname" value
 * @method Contact             setLastname()       Sets the current record's "lastname" value
 * @method Contact             setGender()         Sets the current record's "gender" value
 * @method Contact             setEmail()          Sets the current record's "email" value
 * @method Contact             setHomePhone()      Sets the current record's "home_phone" value
 * @method Contact             setOfficePhone()    Sets the current record's "office_phone" value
 * @method Contact             setMobilePhone()    Sets the current record's "mobile_phone" value
 * @method Contact             setRpm()            Sets the current record's "rpm" value
 * @method Contact             setRpc()            Sets the current record's "rpc" value
 * @method Contact             setNextel()         Sets the current record's "nextel" value
 * @method Contact             setFax()            Sets the current record's "fax" value
 * @method Contact             setAddressHome()    Sets the current record's "address_home" value
 * @method Contact             setAddressWork()    Sets the current record's "address_work" value
 * @method Contact             setDescription()    Sets the current record's "description" value
 * @method Contact             setPrefix()         Sets the current record's "prefix" value
 * @method Contact             setActive()         Sets the current record's "active" value
 * @method Contact             setPatients()       Sets the current record's "Patients" collection
 * @method Contact             setContactPatient() Sets the current record's "ContactPatient" collection
 * 
 * @package    saludonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContact extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_contact');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('firstname', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));
        $this->hasColumn('lastname', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));
        $this->hasColumn('gender', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => false,
             ));
        $this->hasColumn('home_phone', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => false,
             ));
        $this->hasColumn('office_phone', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => false,
             ));
        $this->hasColumn('mobile_phone', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => false,
             ));
        $this->hasColumn('rpm', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => false,
             ));
        $this->hasColumn('rpc', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => false,
             ));
        $this->hasColumn('nextel', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => false,
             ));
        $this->hasColumn('fax', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => false,
             ));
        $this->hasColumn('address_home', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => false,
             ));
        $this->hasColumn('address_work', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => false,
             ));
        $this->hasColumn('description', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             'notnull' => false,
             ));
        $this->hasColumn('prefix', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 1,
             ));


        $this->index('i_firstname', array(
             'fields' => 
             array(
              0 => 'firstname',
             ),
             ));
        $this->index('i_lastname', array(
             'fields' => 
             array(
              0 => 'lastname',
             ),
             ));
        $this->index('i_active', array(
             'fields' => 
             array(
              0 => 'active',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Patient as Patients', array(
             'refClass' => 'ContactPatient',
             'local' => 'contact_id',
             'foreign' => 'patient_id'));

        $this->hasMany('ContactPatient', array(
             'local' => 'id',
             'foreign' => 'contact_id'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'firstname',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
    }
}