<?php

/**
 * BaseHeight
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $profile_id
 * @property decimal $current_height
 * @property date $date_of_height
 * @property string $description
 * @property string $active
 * @property Profile $Profile
 * 
 * @method integer getId()             Returns the current record's "id" value
 * @method integer getProfileId()      Returns the current record's "profile_id" value
 * @method decimal getCurrentHeight()  Returns the current record's "current_height" value
 * @method date    getDateOfHeight()   Returns the current record's "date_of_height" value
 * @method string  getDescription()    Returns the current record's "description" value
 * @method string  getActive()         Returns the current record's "active" value
 * @method Profile getProfile()        Returns the current record's "Profile" value
 * @method Height  setId()             Sets the current record's "id" value
 * @method Height  setProfileId()      Sets the current record's "profile_id" value
 * @method Height  setCurrentHeight()  Sets the current record's "current_height" value
 * @method Height  setDateOfHeight()   Sets the current record's "date_of_height" value
 * @method Height  setDescription()    Sets the current record's "description" value
 * @method Height  setActive()         Sets the current record's "active" value
 * @method Height  setProfile()        Sets the current record's "Profile" value
 * 
 * @package    saludonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHeight extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_height');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('profile_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'notnull' => true,
             ));
        $this->hasColumn('current_height', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => 2,
             ));
        $this->hasColumn('date_of_height', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('description', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('i_current_height', array(
             'fields' => 
             array(
              0 => 'current_height',
             ),
             ));
        $this->index('i_active', array(
             'fields' => 
             array(
              0 => 'active',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'profile_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}