<?php

/**
 * BasePostIndex
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $post_id
 * @property string $title
 * @property string $content
 * @property Post $Post
 * 
 * @method integer   getId()      Returns the current record's "id" value
 * @method integer   getPostId()  Returns the current record's "post_id" value
 * @method string    getTitle()   Returns the current record's "title" value
 * @method string    getContent() Returns the current record's "content" value
 * @method Post      getPost()    Returns the current record's "Post" value
 * @method PostIndex setId()      Sets the current record's "id" value
 * @method PostIndex setPostId()  Sets the current record's "post_id" value
 * @method PostIndex setTitle()   Sets the current record's "title" value
 * @method PostIndex setContent() Sets the current record's "content" value
 * @method PostIndex setPost()    Sets the current record's "Post" value
 * 
 * @package    saludonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostIndex extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_post_index');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('post_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => true,
             ));
        $this->hasColumn('content', 'string', 20000, array(
             'type' => 'string',
             'length' => 20000,
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
    }
}