prod:
  logger:
    class:                   sfNoLogger
    param:
      level:                 err
      loggers:               ~

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none

dev:
  mailer:
    param:
      delivery_strategy: none

all:
  routing:
    class:                   sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  storage:
    class:                   sfSessionStorage
    param:
      session_name:          adminsaludonline
      
  user:
    class:                   UserBackend
    param:
      timeout:               1800
      logging:               %SF_LOGGING_ENABLED%
      use_flash:             true
      default_culture:       %SF_DEFAULT_CULTURE%