<?php

/**
 * ChapterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChapterTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChapterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Chapter');
    }
}