<?php

/**
 * CommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentTable extends DoctrineTable
{
  public function getQueryForLastComments($limit)
  {
    $q = $this->createAliasQuery()
         ->orderBy('c.datetime DESC')
         ->limit($limit);
         
    return $q;
  }    
  public function findLastComments($limit = 10)
  {
    return $this->getQueryForLastComments($limit)->execute();
  }
}