<?php

/**
 * Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    saludonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Comment extends BaseComment
{
  public function save(Doctrine_Connection $conn = null)
  {
    if ($this->isNew() && sfContext::hasInstance())
    {
      $this->setDatetime(date('Y-m-d H:i:s'));
    }
    
    parent::save($conn);
  }
}
