<?php

/**
 * CompanyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompanyTable extends DoctrineTable
{
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Company');
  }
  const
    STATUS_ACTIVE       = 1,
    STATUS_INACTIVE     = 0;
    
  protected static
    $status                = array
                             (
                               self::STATUS_ACTIVE     => 'Yes',
                               self::STATUS_INACTIVE   => 'No',
                             );
                             
  public function getStatuss()
  {
    return self::$status;
  }	
  
  public function getPathDir()
  {
    return sfConfig::get('app_company_dir');
  }
  
  public function getImagePath()
  {
    return sfConfig::get('app_company_path');
  }
}