<?php

/**
 * ContactPatientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactPatientTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactPatientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactPatient');
    }
}