<?php

/**
 * ContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contact');
    }
  const
    STATUS_A     = 1,
    STATUS_B     = 2,
    STATUS_C     = 3,
    STATUS_D     = 4,
    GENDER_MALE            = 'M',
    GENDER_FAME            = 'F';
    
  protected static
    $prefixes                = array
                             (
                               ''               => 'Seleccionar',
                               self::STATUS_A   => 'Sr.',
                               self::STATUS_B   => 'Sra.',
                               self::STATUS_C   => 'Srta.',
                               self::STATUS_D   => 'Dr.',
                             );
                             
  public function getPrefixs()
  {
    return self::$prefixes;
  }    

      
  protected static
    $gender                = array
                             (
                               self::GENDER_MALE => 'Masculino',
                               self::GENDER_FAME   => 'Femenino',
                             );    
  
  public function getGenders()
  {
    return self::$gender;
  }   
}
