<?php

/**
 * DoctorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DoctorTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DoctorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Doctor');
    }
  public function findByNameLike($name, $limit = 20)
  {
    $q = $this->createAliasQuery('d')

         ->where('LOWER(d.firstname) LIKE ?', '%'.Stringkit::strtolower($name).'%')
          ->orwhere('LOWER(d.lastname) LIKE ?', '%'.Stringkit::strtolower($name).'%')
         ->limit($limit);
    
    return $q->execute();
  }      
  const
    GENDER_MALE            = 'M',
    GENDER_FAME            = 'F';
    
  

      
  protected static
    $gender                = array
                             (
                               self::GENDER_MALE => 'Masculino',
                               self::GENDER_FAME   => 'Femenino',
                             );    
  
  public function getGenders()
  {
    return self::$gender;
  }     
}