<?php

/**
 * DoctorHospitalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DoctorHospitalTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DoctorHospitalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DoctorHospital');
    }
}