<?php

/**
 * Doctor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    saludonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Doctor extends BaseDoctor
{
  public function getFullname()
  {
    return sprintf("%s %s", $this->getFirstname(), $this->getLastname());
  }
  public function getGenderStr()
  {  	
    $genders = $this->getTable()->getGenders();
    return $genders[$this->getGender()];
  }  
  public function getFormattedCreatedAt($format = 'D')
  {
    return $this->getTable()->getDateTimeFormatter()->format($this->getCreatedAt(), $format);
  }  
  
  public function getAllHospitalNames()
  {
    $result = '';
    foreach($this->getHospitals() as $hospital) 
    {
      $result.=sprintf("%s | ",$hospital->getName());
    }
    return $result;
  }  
}