<?php

/**
 * DoctorPatientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DoctorPatientTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DoctorPatientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DoctorPatient');
    }
}