<?php

/**
 * HospitalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HospitalTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HospitalTable
     */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Hospital');
  }
  public function findByNameLike($name, $limit = 20)
  {
    $q = $this->createAliasQuery('h')

         ->where('LOWER(h.name) LIKE ?', '%'.Stringkit::strtolower($name).'%')
          //->orwhere('LOWER(d.lastname) LIKE ?', '%'.Stringkit::strtolower($name).'%')
         ->limit($limit);
    
    return $q->execute();
  }     
}