<?php

/**
 * PatientProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PatientProfileTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PatientProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PatientProfile');
    }
}