<?php

/**
 * PostIndexTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostIndexTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostIndexTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostIndex');
    }
}