<?php

/**
 * ProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileTable extends DoctrineTable
{
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Profile');
  }
  
  const
    GENDER_MALE            = 'M',
    GENDER_FAME            = 'F',
    TYPE_FATHER            = 'P',
    TYPE_MATHER            = 'M',          
    TYPE_SONS              = 'H',
    BLOOD_TYPE_AP          = 1,
    BLOOD_TYPE_BP          = 2,
    BLOOD_TYPE_ABP         = 3,
    BLOOD_TYPE_OP          = 4,
    BLOOD_TYPE_AM          = 5,
    BLOOD_TYPE_BM          = 6,
    BLOOD_TYPE_ABM         = 7,
    BLOOD_TYPE_OM          = 8,
    MARITAL_STATUS_MARRIED = 1,
    MARITAL_STATUS_ALIVE   = 2,
    MARITAL_STATUS_NOMARRI = 3;
      
  protected static
    $gender                = array
                             (
                               self::GENDER_MALE => 'Masculino',
                               self::GENDER_FAME   => 'Femenino',
                             );  
  protected static
    $type                  = array
                             (
                               self::TYPE_FATHER => 'Padre',
                               self::TYPE_MATHER   => 'Madre',
                               self::TYPE_SONS   => 'Hijo/Hija',
                             );  
  protected static
    $blood_type            = array
                             (
                               ''                    => 'Seleccionar',
                               self::BLOOD_TYPE_AP   => 'A+' ,
                               self::BLOOD_TYPE_BP   => 'B+' ,
                               self::BLOOD_TYPE_ABP  => 'AB+',
                               self::BLOOD_TYPE_OP   => 'O+' ,
                               self::BLOOD_TYPE_AM   => 'A-' ,
                               self::BLOOD_TYPE_BM   => 'B-' ,
                               self::BLOOD_TYPE_ABM  => 'AB-',
                               self::BLOOD_TYPE_OM   => 'O-'
                             );  
  protected static
    $marital_status        = array
                             (
                               self::MARITAL_STATUS_MARRIED   => 'Casado(a)' ,
                               self::MARITAL_STATUS_ALIVE   => 'Conviviente' ,
                               self::MARITAL_STATUS_NOMARRI  => 'Soltero(a)'
                             );    
  
      

      
                              
  public function getGenders()
  {
    return self::$gender;
  }    
  public function getTypes()
  {
    return self::$type;
  }   

  public function getBloodTypes()
  {
    return self::$blood_type;
  }  
  public function getMaritalStatuss()
  {
    return self::$marital_status;
  }   
    
  public function getPathDir()
  {
    return sfConfig::get('app_profile_dir');
  }
  
  public function getImagePath()
  {
    return sfConfig::get('app_profile_path');
  }      
}