<?php

/**
 * ResourcePatientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourcePatientTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourcePatientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResourcePatient');
    }
}