<?php

/**
 * Resource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    saludonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Resource extends BaseResource
{
  public function generatePathFilename($file)
  {
    $this->setSize(filesize($file->getTempName()));
    $this->setFullMime($file->getType());
    
    return Stringkit::fixFilename($file->getOriginalName()).'_'.rand(11111, 99999).$file->getOriginalExtension();
  }
  public function save(Doctrine_Connection $conn = null)
  {
    $this->createThumbnail('path', $this->getFullMime() );
    parent::save($conn);
    
  } 
  
  public function getFormattedCreatedAt($format = 'D')
  {
    return $this->getTable()->getDateTimeFormatter()->format($this->getCreatedAt(), $format);
  }    
}