<?php

/**
 * ResourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourceTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Resource');
    }
    
  public function getPathDir()
  {
    return sfConfig::get('app_resource_dir');
  }
  
  public function getPathPath()
  {
    return sfConfig::get('app_resource_path');
  }
  
    
}