<?php

/**
 * SponsorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SponsorTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SponsorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sponsor');
    }
}