<?php

/**
 * TreatmentDiagnosisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TreatmentDiagnosisTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TreatmentDiagnosisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TreatmentDiagnosis');
    }
}