<?php

/**
 * Treatment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    saludonline
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@datasolutions.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Treatment extends BaseTreatment
{
  public function getSlug()
  {
    return $this->getId();
  }
  
  public function getFormattedDateOfTreatment($format = 'D')
  {
    return $this->getTable()->getDateTimeFormatter()->format($this->getDateOfTreatment(), $format);
  }
  
  public function getDiagnosisNames()
  {
  	$result = '';
    foreach($this->getDiagnosises() as $diagnosis) 
    {
      $result.=sprintf("<li>%s</li>",$diagnosis->getRealName());
    }
    return sprintf('<ul>%s</ul>',$result);
  }
}