<?php

/**
 * TreatmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TreatmentTable extends DoctrineTable
{
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Treatment');
    }
  public function findOneBySlug($slug)
  {
    $q = $this->createAliasQuery()
         ->where('t.id = ?', $slug);
         
    return $q->fetchOne();
  }  
  
  public function getQueryForLastTreatments($limit, $profile_id)
  {
    $q = $this->createAliasQuery()
         ->orderBy('t.date_of_treatment DESC')
         ->limit($limit);
    
    if($profile_id)
    {
        $q->addWhere('t.profile_id = ?', $profile_id);
    }
         
    return $q;
  }
  
  public function findLastTreatments($limit = 4, $profile_id = null)
  {
    return $this->getQueryForLastTreatments($limit, $profile_id)->execute();
  }      
}