<?php

/**
 * WeightTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WeightTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WeightTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Weight');
    }
  public function findOneBySlug($slug)
  {
    $q = $this->createAliasQuery()
         ->where('w.id = ?', $slug);
         
    return $q->fetchOne();
  }  
  
  public function getQueryForLastWeights($limit, $profile_id, $order = 'DESC')
  {
    $q = $this->createAliasQuery()
         ->orderBy('w.date_of_weight '.$order)
         ->limit($limit);
    
    if($profile_id)
    {
        $q->addWhere('w.profile_id = ?', $profile_id);
    }
         
    return $q;
  }
  
  public function findLastWeights($limit = 4, $profile_id = null, $order = 'DESC')
  {
    return $this->getQueryForLastWeights($limit, $profile_id, $order)->execute();
  }  
}