Category:
  tableName:                           t_category
  actAs:
    SluggableExt:                      { fields: [ name ] }
    Timestampable:
  columns:
    id:                                { type: integer  , length: 20 , primary: true    , autoincrement: true                                                  }
    name:                              { type: string   , length: 100                   , notnull: true                                                        }
  indexes:
    u_name:                            { fields: [ name ]                               , type: unique                                                         }
  relations:
    Post:                              { class: Post             , local: category_id   , foreign: post_id  , alias: Posts, refClass: PostCategory             }
  options:
    symfony:                           { filter: false, form: true }
    
    
PostCategory:
  tableName:                           t_post_category
  actAs:
    Timestampable:                     { updated: { disabled: true } }
  columns:
    post_id:                           { type: integer  , length: 20 , primary: true                                                                           }
    category_id:                       { type: integer  , length: 20 , primary: true                                                                           }
  relations:
    Post:                              { class: Post             , local: post_id       , foreign: id, type: one , alias: Post    , onDelete: CASCADE , onUpdate: CASCADE }
    Category:                          { class: Category         , local: category_id   , foreign: id, type: one , alias: Category, onDelete: CASCADE , onUpdate: CASCADE }
  options:
    symfony:                           { filter: false, form: false }
    